### ISSUE TITLE
Some distributions missing on cpancover.com

### ISSUE THREAD

**Issue by wollmers** [pjcj/Devel--Cover#106]
Seems that the initial reports where based on a cpan index of a certain date, and uploads since then where not reported during the initial phase. Workaround for me was to upload a new release, an the report appeared wthin minutes.

**Comment by pjcj** [comment]
cpancover has gone through a few iterations in the meantime, and I think this problem has been fixed.  So I'm going to close the ticket.  If you notice anything missing though, please feel free to reopen it with more information.

Thanks a lot for your report, and for all your help with cpancover.
