### ISSUE TITLE
Browsing by letters result in 404

### ISSUE THREAD

**Issue by jonasbn** [pjcj/Devel--Cover#115]
I tried to browse using the letter index on:

http://cpancover.com/latest/index.html

But all I get is 404s :-(

jonasbn

**Comment by zoffixznet** [comment]
Same.

**Comment by pjcj** [comment]
This is an intermittent problem.  It occurs when the new reports are being generated for large modules (or modules producing lots of coverage information), I think.  It has resisted my attempts to fix it in odd moments that I have found so I have slated some time to sort it out during the QA Hackathon in Berlin in a few weeks.  It's probably just some silly little thing, but hopefully it will get sorted soon.

In the meantime, just waiting for a little while should allow you to see the page.

Thanks both for taking the time to report it, and sorry not have it sorted yet.

**Comment by pjcj** [comment]
Fixed with 1495809.
