### ISSUE TITLE
Bleadperl v5.21.4-129-g354b74a breaks PJCJ/Devel-Cover-1.17.tar.gz

### ISSUE THREAD

**Issue by andk** [pjcj/Devel--Cover#122]
There is a ticket with the subject 'Bleadperl v5.21.4-129-g354b74a breaks PJCJ/Devel-Cover-1.17.tar.gz' at https://rt.perl.org/Public/Bug/Display.html?id=122874

The content still holds for 1.18.

**Comment by pjcj** [comment]
Thanks very much, as ever, for finding and reporting this in so much detail.

Fixed with 745d1dfb3b497332c72982e5a27fae79988f60a5
