### ISSUE TITLE
cpancover.com stopped working?

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#136]
Net::DNS::SEC 1.00_02 uploaded to CPAN 3 weeks ago.

Usually coverage report appears in a day or two, but this one has not.

**Comment by pjcj** [comment]
You are quite correct, and I apologise.  And it should normally be a matter of minutes before the coverage report is available.

I upgraded the server running cpancover.com, which included a docker upgrade.  The docker upgrade either fixed some bug or changed some API which is stopping the cpancover process from from getting the coverage results.

I plan to have a fix in place this week.

Thanks for noticing and posting the report.

**Comment by rwfranks** [comment]
cpancover.com seems to be working, although the Devel::Cover inside is clearly not

**Comment by pjcj** [comment]
cpancover fixed with c68b8cc
Devel::Cover should be fixed (for this module) with bc3722f
