### ISSUE TITLE
condition coverage is incorrect for conditions with more than 3 operands

### ISSUE THREAD

**Issue by waterbeetle** [pjcj/Devel--Cover#137]
my $condA = 0;
my $condB = 0;
my $condC = 1;
my $condD = 1;
if ($condA || $condB || $condC && $condD)
{
    print "hello\n"; 
}  
has a condition coverage of zero.

**Comment by hknutzen** [comment]
The test case can be simplified.
The error already occurs with exactly 3 operands.

    my ($a, $b, $c) = (0, 1, 1);
    if ($a || $b && $c) {
       print "hello\n";
    }

HTML report again shows 0% coverage.

With "cover -report text" we see:

    or 3 conditions

    line  err      %      l  !l&&r !l&&!r   expr
    ----- --- ------ ------ ------ ------   ----
    2     ***     33      0      0      1   $a or $b and $c

Here we see, that ``!l&&!r`` is erroneously marked with ``1``.
But instead ``!l&&r`` should have been marked.

This has been tested with Devel::Cover version 1.22.

**Comment by pjcj** [comment]
Thanks very much for this report.  The standard HTML report does have some bad logic around this area and I will check to see whether this is the problem.  The textual report should be reporting accurately what Devel::Cover thinks is taking place and it does seem that the wrong condition is being marked as covered, as you have reported.

**Comment by hknutzen** [comment]
My previous test case was run with perl 5.22.0.
When switching to perl 5.12.3 (my oldest available version in perlbrew), the output of ``cover -report text`` shows the expected output:

    or 3 conditions

    line  err      %      l  !l&&r !l&&!r   expr
    ----- --- ------ ------ ------ ------   ----
    6     ***     33      0      1      0   $a or $b and $c

**Comment by pjcj** [comment]
This behaviour changed with perl 5.16.0.  Not sure why yet ...

**Comment by pjcj** [comment]
Looks like I fixed this but didn't close the ticket, so I'll do that now.

Thanks @waterbeetle and @hknutzen.

@waterbeetle, I have added you to the Contributors file, but all I know about you is your github handle.  I'd be pleased if you would expand on your entry, but I'm also happy for you to leave it as it is or remove the entry as you see fit.

Thanks again.
