### ISSUE TITLE
Devel::Cover fails on perl 5.22.0

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#140]
make test for Net::DNS 1.01_04 using perl 5.18.4

All tests completed successfully

$ du -sk cover_db/
3796	cover_db/

make test for Net::DNS 1.01_04 using perl 5.18.4

All tests completed successfully

$ du -sk cover_db/
308	cover_db/

An extreme case of this, using a single test script containing only the line  "use Net::DNS;" produces nothing at all.

**Comment by rwfranks** [comment]
Devel::Cover database gets destroyed by
  use Socket;
at Net::DNS::Resolver::Base, line 14

**Comment by pjcj** [comment]
Thanks very much for reporting this!  Is should be fixed by bc3722fdc6aab83ad10f05665aa65e1ce4756e24
