### ISSUE TITLE
Deep recursion on subroutine "B::Deparse::_pessimise_walk_exe"

### ISSUE THREAD

**Issue by garu** [pjcj/Devel--Cover#142]
Hi Paul!

I feel like I haven't said this enough, so thank you SO MUCH for all the incredible work you do on Devel::Cover. It's a great piece of software.

Recently I have found this project using perl-5.20.1 under plenv and Devel::Cover 1.21 and it's giving me the following output:

```
$ PERL5OPT=-MDevel::Cover carton exec -- prove -lvwr t/unit/mytest.t
...
1..7
Deep recursion on subroutine "B::Deparse::_pessimise_walk_exe" at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 396.
Use of uninitialized value $expr in concatenation (.) or string at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 1380.
Deep recursion on subroutine "B::Deparse::_pessimise_walk_exe" at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 396.
Use of uninitialized value $expr in concatenation (.) or string at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 1380.
Use of uninitialized value $expr in concatenation (.) or string at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 1380.
Use of uninitialized value $expr in concatenation (.) or string at /Users/garu/.plenv/versions/myperl/lib/perl5/5.20.1/B/Deparse.pm line 1380.
ok
All tests successful.
Files=1, Tests=7, 36 wallclock secs ( 0.07 usr  0.02 sys + 34.57 cusr  0.76 csys = 35.42 CPU)
Result: PASS
```
After this, if I try and run it again, it dies before running any tests, with this message:

```
Can't read /Users/garu/MyProject/cover_db/digests with JSON: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "=\x{f3}rl\x{3}\x{0}(...") at /Users/garu/.plenv/versions/myperl/lib/perl5/site_perl/5.20.1/darwin-2level/Devel/Cover/DB/IO/JSON.pm line 40.
BEGIN failed--compilation aborted at /Users/garu/.plenv/versions/myperl/bin/carton line 5.
```
Any ideas as to what am I doing wrong?

Cheers!

**Comment by pjcj** [comment]
I'm sure you're not doing anything wrong.  It seems like a real bug.

At times I have hit the deep resursion limit legitimately, and at times I have also had problems with B::Deparse due to feeding it input it doesn't usually receive, which usually results in a patch to B::Deparse.

I suspect that the JSON errors the second time are due to the initial erros, but I can't immediately see what could be in the digests file.

Is there any way I could try to reproduce this locally?

Thanks for your kind comments, and right back at you for all you do!

**Comment by garu** [comment]
Ok. After talking to @pjcj during the QA Hackathon it looks like B::Deparse is blowing up due to a deep traversal of dependencies, since once we ignore carton's `local` directory (via `PERL5OPT=-MDevel::Cover=ignore,local carton exec -- prove -lvwr t/unit/mytest.t`) the issue goes away. Oddly enough, it also goes away completely if we add this to line 1660:

```perl
if (!defined $expr) {
    require Carp; Carp::confess('here!');
}
```
We're trying to get Leon Timmermanns to help us fix B::Deparse.
