### ISSUE TITLE
cpancover.com stopped working again?

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#144]
$ wget http://cpancover.com/latest/dist/N.html
--2015-10-08 15:54:15--  http://cpancover.com/latest/dist/N.html
Resolving cpancover.com (cpancover.com)... 213.138.101.218
Connecting to cpancover.com (cpancover.com)|213.138.101.218|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2015-10-08 15:56:22--  (try: 2)  http://cpancover.com/latest/dist/N.html
Connecting to cpancover.com (cpancover.com)|213.138.101.218|:80... connected.
HTTP request sent, awaiting response...

**Comment by pjcj** [comment]
Looks like the server crashed - should be back up again now.

Thanks for noticing and reporting!
