### ISSUE TITLE
cpancover.com stopped working again?

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#149]
Usually results appear within a few hours

This is hard to detect without throwing in more stuff in CPAN

Perhaps the main page needs to display time when last report was added to database.
Maybe restart automatically if nothing happens within TBD hours

**Comment by pjcj** [comment]
I have been trying to gradually improve things on cpancover, and I think things are getting better, but I am not particularly happy with everything yet.

Thanks for noticing and for your messages.
