### ISSUE TITLE
Suggestion: Touch coverage.html after html generation to float it to top in file managers

### ISSUE THREAD

**Issue by wchristian** [pjcj/Devel--Cover#158]
I usually sort my file manager by date, and it would be very useful if coverage.html was touched at the end of the process to make it show up at the top of the list.

**Comment by pjcj** [comment]
Good idea! Done with c7b7e6f38e2242d6a2a0100b16dc3e0e037f1dd4

Thanks very much.

**Comment by wchristian** [comment]
Awesome, thank you! :D
