### ISSUE TITLE
No longer builds on blead: -DPERL_OP_PARENT is now default

### ISSUE THREAD

**Issue by ribasushi** [pjcj/Devel--Cover#161]
See https://travis-ci.org/dbsrgits/dbix-class/jobs/130869166#L1089-L1098

**Comment by pjcj** [comment]
Ah, yes, I had been expecting that.  Thanks.

**Comment by mat813** [comment]
👍

**Comment by pjcj** [comment]
See https://github.com/mhx/Devel-PPPort/issues/35 (thanks @karenetheridge)

**Comment by pjcj** [comment]
This is now fixed in 1.24.  Thanks to everyone who has helped to get it fixed in any way.
