### ISSUE TITLE
cover script broken

### ISSUE THREAD

**Issue by SBECK-github** [pjcj/Devel--Cover#163]
When passing in multiple -ignore or -select options, only one file is actually ignored.  The problem is in the cover script at line 241.

The statement:

```
map quotemeta glob, @{$Options->{ignore}};
```

does not work.  However, the following DOES work:

   map quotemeta, map glob, @{$Options->{ignore}};

Similar for the -select option a couple lines later.  This is with perl 5.18.2 .

**Comment by pjcj** [comment]
Thank you very much for finding and reporting this.  I have made the changes you have suggested with 52b71ab06bc0e4d0a5a413f6da0ae396127b2626

I have also added you to the Contributors file.  Please feel free to change or delete your entry there as you see fit.

Thanks again
