### ISSUE TITLE
Need documentation change for "count"

### ISSUE THREAD

**Issue by kbrannen** [pjcj/Devel--Cover#167]
The doc says about statements:

```
   If there are multiple statements (or any other criterion) on a line you can specify
   which statement is uncoverable by using the "count" attribute, count:n, which
   indicates that the uncoverable statement is the nth statement on the line.
```

I struggled with:

```
if (normal_condition)      { code }
elsif (fallback_condition) { code }
else                       { die "you failed horribly" }
```

That "else" should never be call and I couldn't figure out how to tell Devel::Cover that. I finally started to wonder about that "or any other criterion" part on count and if it meant that it could be applied to branches too (not just statements). After a couple of tries figured out I could do:

```
# uncoverable branch false count:2
if (normal_condition)      { code }
elsif (fallback_condition) { code }
else                       { die "you failed horribly"; }
```

So I would propose adding to the docs to explain this, in the "Branches" sub-sub-section, new material in bold:

```
   Both branches may be uncoverable:

       ### current example, unchanged

   ** For more complex branching the "count" attribute can be used here too. For example:

   # uncoverable branch false count:2
   if (normal_check()) {
       handle_normal();
   } elsif (safety_check()) {
       handle_fallback();
   } else {
       die "fatal situation found!"; # uncoverable statement
   }

   This marks the "else" as not being coverable. **
```

It just occurred to me, there might be an issue with _for (condition) { when (x) {} when (y) {} default {} }_ in that the developer believes the default would never be called. An example of how to deal with that would be nice too. :) My first try would be to put "# uncoverable branch true count:3" just above the "for", but I could see that being wrong, and if so, I don't know where I'd put the directive.

I have yet to find or think of a situation where you'd need "count" on "conditions", but if there is, it'd be nice to put a note and example there too.

Thanks,
Kevin

**Comment by pjcj** [comment]
Thank you very much for this.  I have added an additional section to the _uncoverable_ test to cover this, and I have added some extra documentation based on your suggestions.  See 878ab7dff7844907d7e678f39333cf220167dc18

I've also added you to the contributors file - please feel free to amend or remove your entry as you see fit.

Thanks again for your suggestion and sorry it took me so long to get to it.
