### ISSUE TITLE
cpancover.com:  inconsistent perl revs

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#169]
Unexpected warning in session log

...
***\* Checking coverage of Net-DNS-1.06_02 ****
Testing Net-DNS-1.06_02 in /root/.cpan/build/Net-DNS-1.06_02-U4ksyy
Deleting database /root/.cpan/build/Net-DNS-1.06_02-U4ksyy/cover_db
cover: running make test "OPTIMIZE=-O0 -fprofile-arcs -ftest-coverage" "OTHERLDFLAGS=-fprofile-arcs -ftest-coverage"
PERL_DL_NONLAZY=1 "/usr/local/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/_.t

This version of Devel::Cover was built with Perl version 5.022001.
It is now being run with Perl version 5.022000.
Attempting to make adjustments, but you may find that some of your modules do
not have coverage data collected.  You may need to alter the +-inc, +-ignore
and +-select options.
...

**Comment by pjcj** [comment]
I think this must have been just a mistake when I was updating cpancover.  Everything seems OK with 1.12 now, at least as far as this is concerned.  Although there is a "Use of uninitialized value" warning.  I'll look into that later, but I'll close this now.  Thanks a lot for reporting it.
