### ISSUE TITLE
[PATCH] Make the build reproducible

### ISSUE THREAD

**Issue by gregoa** [pjcj/Devel--Cover#170]
In Debian we are currently applying the following patch to
Devel-Cover.
We thought you might be interested in it too.

```
Description: Make the build reproducible
Author: Chris Lamb <lamby@debian.org>
Reviewed-by: gregor herrmann <gregoa@debian.org>
Last-Update: 2016-08-31
Bug-Debian: https://bugs.debian.org/835871
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdevel-cover-perl.git/plain/debian/patches/reproducible-build.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by pjcj** [comment]
Thanks very much for this.  I have made a slightly different fix.  If we are going to turn a variable into a constant then there's not much need to have it as a variable at all, so I have removed it.

I'm slightly concerned that it might have been needed for some other reason, but I suppose we'll find that out in time.

The change is e25aadbfc7bcd7aada83b188ec73da8874ec3983 and it will mean that your patch will neither apply nor be needed.

Thanks again,
