### ISSUE TITLE
[PATCH] fix spelling mistakes

### ISSUE THREAD

**Issue by gregoa** [pjcj/Devel--Cover#171]
In Debian we are currently applying the following patch to
Devel-Cover.
We thought you might be interested in it too.

```
Description: fix spelling mistakes
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2016-08-31
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdevel-cover-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by pjcj** [comment]
Thank you very much for this! One typo followed by copy and paste without thought ;)

I have applied this with 19efbbd and it will be in the next release.
