### ISSUE TITLE
[Feature Add] support multiple report formats in the cover script

### ISSUE THREAD

**Issue by edenhochbaum** [pjcj/Devel--Cover#172]
I'd like to run cover and flush the internal representation to multiple report formats, e.g., html & json.  The script doesn't currently support this.  

Would a pull request to support this meet much resistance?

**Comment by pjcj** [comment]
Hello,

Are you saying you would like to run multiple reports in a single "cover" invocation?  I have never found that necessary, but I am not against it in principle.

Is there a reason not to run cover multiple times instead?  I suppose that it might be a pain if there are many parameters to pass.  Or perhaps the cover DB is large and multiple invocations is much slower?

So no, probably not much resistance, but I would like to discuss the motivation and talk through the architecture before getting too deep into implementation.

Thanks for your interest!

**Comment by xtaran** [comment]
I can imagine that this is useful in e.g. reporting coverage to multiple webservices at the same time, like e.g. https://codecov.io/ and https://coveralls.io/. I currently run tests and report generation separated: First do all the tests, then generate two reports (in two separate commands) from it.

**Comment by edenhochbaum** [comment]
Great, thanks for the responses, and thanks for the tool!

Let me try to give a high-level description of how I understand this to work for one very simple case.  If my high-level understanding is wrong, then it would be very helpful for me if someone could identify that.  

Okay, so we have a perl script (cover) that takes as input (1) a description of some information we want it to acquire (e.g., coverage data for script X.pl) and (2) a description of how we want that information output (e.g., as an HTML report.)

The script (cover) proceeds to gather-and-store that information (code coverage metrics) in an internal  perl-data-structure (DB) representation.  It then converts from the internal perl-data-structure representation to the desired output filestream representation (e.g., it takes the perl-data-structure and maps it to an HTML representation.)

Finally, the script shuts down without persistently storing the internal DB perl-data-structure representation in any kind of canonical representation.

Is that correct?  If so, and if I want to get code coverage data reported in 2 formats, then it seems like I have to generate the internal perl-structure (DB) representation twice, which may be costly.  That was the situation I wanted to avoid.

Thanks!

**Comment by pjcj** [comment]
@xtaran yes, that is a good use case - thanks

@edenhochbaum I think your understanding is basically correct, yes.  There is persistent storage of the DB and, depending on how you want to look at it, you could even call it canonical.  You can use either Storable, JSON or Serial backends for storage.  But the cost of reading that in can be expensive.  So your reasoning here is the same as mine when I said that it might be slow.

So your idea would be to pass in multiple reports on the command line and then loop through them, rather than only allowing one to be passed in?  If so then I am in favour of that approach.  I also wonder whether we might be able to generate the reports in parallel too.  That might be nice but shouldn't prevent the simpler looping solution.

**Comment by edenhochbaum** [comment]
That's exactly right, my idea would be to support passing in multiple report formats, and just looping over the formats sequentially.  Thanks for the help here.  I'll attach the pull request here, when it's prepared.

**Comment by edenhochbaum** [comment]
So I looked at the existing code, and this change seems more involving than I'd anticipated.  Basically, the `$Options` hash is being used as a kind of global scratch pad for the cover script.  It's being modified in-place by the various formats downstream from calls to `$format->get_options($Options)`, and then that modified structure is used to generate the `$db`.

So this isn't the simple pipeline I'd imagined with a "format" implementation taking-in a `$db` and some independent options from the cover script as input, and generating filestream output.  Rather, the "format" influences the generation of the `$db`, and the cover script uses the "format" to determine what options should be passed to the "format" later in execution.

At a high-level, is it necessary to have the "formats" modifying the cover script's lexical `$Options` variable in-place?

**Comment by pjcj** [comment]
I've finally got back to this and have implemented the feature in 79545c898c40406cdbc81945bcdff395551a5492.  Thanks very much for the suggestion.

If I were starting from scratch I would do things slightly differently, but for now I think this works well enough.

@edenhochbaum, I have added you to the Contributors file.  Please feel free to amend or remove your entry as you see fit.

Thanks again!
