### ISSUE TITLE
Devel::Cover not passing tests on perl-5.25.1 forward

### ISSUE THREAD

**Issue by jkeenan** [pjcj/Devel--Cover#181]
See reports here:  http://matrix.cpantesters.org/?dist=Devel-Cover

**Comment by pjcj** [comment]
This should be fixed in 1.24. No cpantesters reports for 1.24 have come through yet, but I'm confident so I'm going to close this.

Thanks very much for the report!

**Comment by jkeenan** [comment]
On 04/20/2017 04:47 PM, Paul Johnson wrote:
> This should be fixed in 1.24. No cpantesters reports for 1.24 have come
> through yet, but I'm confident so I'm going to close this.
>
> Thanks very much for the report!
>

I was doing a 'minicpan' update and spotted this in the list of updated 
distros.  I then tried it out on perl 5 blead with 
PERL_USE_UNSAFE_INC=0.  That is, under very strict conditions.  All 
tests PASSed and Devel::Cover was installed -- which means it's 99.99% 
certain it will install under perl-5.26.0.

Thanks for your ongoing efforts and investigation!

Jim Keenan
