### ISSUE TITLE
Uncoverable path when using ||= operator

### ISSUE THREAD

**Issue by KES777** [pjcj/Devel--Cover#182]
I have this code:

    $controller ||=  PL( $name );

When I have both cover both cases: when $controller is FALSE and TRUE
I still get report from Devel::Cover about only 67% coverage

```
$ perl -MO=Concise -e '$xx ||= 3'
7  <@> leave[1 ref] vKP/REFC ->(end)
1     <0> enter ->2
2     <;> nextstate(main 1 -e:1) v:{ ->3
-     <1> null vK/1 ->7
4        <|> orassign(other->5) vK/1 ->7
-           <1> ex-rv2sv sKRM/1 ->4
3              <$> gvsv(*xx) s ->4
6           <1> sassign sK/BKWARD,1 ->7
5              <$> const(IV 3) s ->6
-e syntax OK
```

**Comment by KES777** [comment]
![coverage](https://cloud.githubusercontent.com/assets/799021/24331422/be32af82-123c-11e7-8a6a-6e74a6b78e23.png)

**Comment by pjcj** [comment]
Thanks very much for your report.  What is happening here is that Devel::Cover is telling you that you have not tested with PL($name) being false.  Now, you may not care about that, but Devel::Cover has no way to know that.

This is essentially the same problem as reported in #154, and there is further discussion there.

We need to come up with a good solution for this, but I am going to close this report and leave #154 as the place to solve this.

Thanks again.

**Comment by KES777** [comment]
ok. thank you for links
