### ISSUE TITLE
Wrong version reported on 5.8.9 under Travis CI

### ISSUE THREAD

**Issue by briandfoy** [pjcj/Devel--Cover#183]
I was tracking down some Perl 5.8.9 failures in Travis CI. I have a [test repo](https://github.com/briandfoy/devel_cover_travis_test) and [its results in Travis](https://travis-ci.org/briandfoy/devel_cover_travis_test).

The version of Devel::Cover they install is something that won't work. I tried to get the version they installed, but the message looks like it has a corrupted version at the beginning. It should be 1.24 in whatever format you had.

	$ perl -MDevel::Cover -le 'print "Devel::Cover version" . Devel::Cover->VERSION';
	================================================================================
									   IMPORTANT
									   ---------
	Devel::Cover 0.001 is not supported on perl 5.008009.

This is the default value of `$LVERSION`, which tries to `eval` the `$VERSION` (which hasn't been set yet).

**Comment by pjcj** [comment]
Thanks very much for this report.  You are quite correct about 0.001 being the default value.  What is really confusing though, is why you see it.  $VERSION should only be unset in the development code.  Any released version of the code has $VERSION set (dzil does that).  So it seems that somehow you are managing to pick up the development code.  Either that or there is some other bug which I can't see.

Do you have any further insight?

**Comment by venupec** [comment]
Hello Paul,

I'm having exactly the same issue. Do we know the root cause??

I'm using perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi and installed Devel::Cover v1.25

But when i run 

`$ perl -MDevel::Cover -e 'print $Devel::Cover::VERSION'`

`Devel::Cover 0.001: Collecting coverage data for branch, condition, pod, statement, subroutine and time.`

<output snipped>

`1.25`

Though the last line has the version # correct, the first line has 0.001. Do we know why?

Much appreciated!!

**Comment by venupec** [comment]
Actually, this is interesting. I've tested on following Devel::Cover versions:

1.09, 1.20, 1.22, 1.23 and 1.24

Up to v1.22 i see the first line as (i've pasted the sample from v1.22)

`Devel::Cover 1.22: Collecting coverage data for branch, condition, statement, subroutine and time.`

But from v1.23 i see the first line as

`Devel::Cover 0.001: Collecting coverage data for branch, condition, statement, subroutine and time.`

So something broke in v1.23 ?

**Comment by pjcj** [comment]
OK, with that information, I presume the offending commit is f979b6f777439b0525a30d3078de02e92fddd702.   Are you able to check this?

I suspect that setting $VERSION (# VERSION) also needs to be inside the BEGIN block for a complete fix.

**Comment by venupec** [comment]
The following code actually displays the right version 1.25.

` 13 our $VERSION; # VERSION`
 ` 14 our $LVERSION;`
  `15 BEGIN {`
  `16     $VERSION = '1.25';`
  `17     $LVERSION = do { no warnings; eval '$VERSION' || "0.001" }`
  `18 }  # for dev`

But i also think we should add a test in `t/internal/criteria.t` ? Something like the following

`is $Devel::Cover::VERSION,`
`   "0.001",`
`   "Devel::Cover VERSION is not picked up correctly..!!";`

**Comment by pjcj** [comment]
I have fixed this with b12cef8f1c94e1112df7de7ab4bf086ee1d7de8a.  It's a different solution but a better one, I think.  Thanks for the initial report and the help in tracking it down.

@briandfoy - I have added you to the Contributors file. Please feel free to amend or remove the entry as you see fit.

@venupec - I'd like to add you too. If you are happy with that please either let me know the entry you would prefer, or just make the change yourself.

Thanks again.
