### ISSUE TITLE
Devel::Cover 1.24 still says it works on >= 5.8., but Devel::Cover thinks otherwise

### ISSUE THREAD

**Issue by briandfoy** [pjcj/Devel--Cover#184]
My Travis CI builds have been breaking this week. [Devel::Cover claims not to support 5.8.9](https://travis-ci.org/briandfoy/devel_cover_travis_test/jobs/225334540) and exits (with faulty message #183 ).

The docs in 1.24, the version I get when I install in Travis with cpanm, still says that it supports 5.8.1. In the code, it's 5.10 or later that works without the environment var shim.

**Comment by pjcj** [comment]
Thanks very much for noticing and reporting this.  I have updated the documentation with 947d461.
