### ISSUE TITLE
Untaint DEVEL_COVER_OPTIONS

### ISSUE THREAD

**Issue by DarthGandalf** [pjcj/Devel--Cover#187]
I tried to pass `DEVEL_COVER_OPTIONS="-db,foo/cover_db"`, and got:
`Insecure dependency in mkdir while running with -T switch at /home/travis/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Devel/Cover.pm line 392.`

Version 1.25

**Comment by pjcj** [comment]
Thanks very much for this report.

I think there is no need to worry about $DEVEL_COVER_OPTIONS being tainted - anyone using Devel::Cover can do a lot worse than setting an environment variable.  So I have untainted the variable in c30a35021daa302ab468909ba418234c3cbd7649

This will be in the next release.

I have added you to the Changes file.  If you'd like to change your entry (add an email address, or change or delete the entry) please either send a pull request or just let me know what changes to make.

Thanks again!

**Comment by DarthGandalf** [comment]
Cool, thanks for the quick fix!

2017-07-24 19:38 GMT+01:00 Paul Johnson <notifications@github.com>:
