### ISSUE TITLE
-coverage pod-also_private-xx not accepted

### ISSUE THREAD

**Issue by showaltb** [pjcj/Devel--Cover#191]
Using Devel::Cover 1.26. I'm trying to ignore Pod coverage for Moose's BUILD and BUILDARGS subs.

Per the documentation:

> You can specify options to some coverage criteria. At the moment only pod coverage takes any options. These are the parameters which are passed into the Pod::Coverage constructor. The extra options are separated by dashes, and you may specify as many as you wish. For example, to specify that all subroutines containing xx are private, call Devel::Cover with the option -coverage,pod-also_private-xx.

However, when I try to use this feature, `cover` exits with an error:

    $ cover -coverage pod-also_private-BUILD
    Unrecognised -coverage: pod-also_private-BUILD at /Users/showaltb/.plenv/versions/5.10.1/bin/cover line 122.

It looks like the code in this area isn't designed to handle such an argument. If I comment out line 122, I get another error later in the process:

    Undefined subroutine pod-also_private-xx called at /Users/showaltb/.plenv/versions/5.10.1/lib/perl5/site_perl/5.10.1/darwin-2level/Devel/Cover/Report/Html_minimal.pm line 22.

**Comment by pjcj** [comment]
Thanks very much for your report.

I think this is a misunderstanding of the documentation.  The options you are reading about are for Devel::Cover itself, not the cover program.  That is, they apply as the coverage is being collected, not as it is being processed.

So you will want to add the options to your invocation of Devel::Cover.  For example: HARNESS_PERL_SWITCHES=-MDevel::Cover=-coverage,pod-also_private-BUILD

I'll close the ticket, but if there's a problem when used in this way, please feel free to reopen it.

Thanks.

**Comment by showaltb** [comment]
Sorry for the confusion on my part.  I was actually using the `cover` program to collect the data as well (with `-test` option), and that let me to believe that I could influence the pod option at that phase. Thanks for clearing it up for me.

**Comment by pjcj** [comment]
Glad it's sorted.  That's a good point though, about `cover -test`.  I'll have a think about whether it makes sense to allow the Devel::Cover options to by specified via `cover` itself when using the `-test` option.

**Comment by balajirama** [comment]
@pjcj I am running into a situation where I have a BUILD method in my class. And I'm using Moose. And cover -test says that BUILD does not have a pod. Shouldn't cover -test take the POD coverage report from t/author-pod-coverage.t ?
