### ISSUE TITLE
--report html_minimal --outputfile index.html stops working in 1.27

### ISSUE THREAD

**Issue by chiselwright** [pjcj/Devel--Cover#194]
I noticed that I was getting weird errors in output after a recent upgrade; I've snipped most of the output for brevity, but it appears that CLI option parsing is no longer occurring correctly in sub-packages:

```
# cpanm --notest Devel::Cover@1.26
Successfully installed Devel-Cover-1.26 (downgraded from 1.27)

# cover --report html_minimal --outputfile index.html --outputdir /tmp/coverage/
…
HTML output written to /tmp/coverage/index.html
done.



# cpanm --notest Devel::Cover@1.27
Successfully installed Devel-Cover-1.27 (upgraded from 1.26)

# cover --report html_minimal --outputfile index.html --outputdir /tmp/coverage/
Can't open database /usr/src/platform/--outputfile
```

**Comment by pjcj** [comment]
Thanks very much for this report.  It should be fixed by ea35cf06f52f25e0c681ae488b8fa6d498f9d48f.

As this is rather serious I'll make a new release as soon as I can.

I've also added you to the contributors file.  Please feel free to amend or remove your entry as you see fit.

Thanks again!
