### ISSUE TITLE
Build testcover compilation failure

### ISSUE THREAD

**Issue by tripled1313** [pjcj/Devel--Cover#197]
When I run ./Build testcover, it fails with this error message

t/validate.t .. Bareword found where operator expected at /apps/ebi/mabel1/perl5/lib/perl5/x86_64-linux-thread-multi/Devel/Cover.pm line 43, near "die $@ if $@ && $@ !~ m/Can't"
  (Might be a runaway multi-line // string starting on line 25)
        (Do you need to predeclare die?)
Backslash found where operator expected at /apps/ebi/mabel1/perl5/lib/perl5/x86_64-linux-thread-multi/Devel/Cover.pm line 43, near "Pod\"
syntax error at /apps/ebi/mabel1/perl5/lib/perl5/x86_64-linux-thread-multi/Devel/Cover.pm line 43, near "die $@ if $@ && $@ !~ m/Can't locate "
BEGIN not safe after errors--compilation aborted at /apps/ebi/mabel1/perl5/lib/perl5/x86_64-linux-thread-multi/Devel/Cover.pm line 48.
Compilation failed in require.
BEGIN failed--compilation aborted.
t/validate.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

In the module Cover.pm line 43 is die $@ if $@ && $@ !~ m/Can't locate Pod\/Coverage.+pm in \@INC/;

which is in this block of code

BEGIN {
    # Use Pod::Coverage if it is available
    eval "use Pod::Coverage 0.06";
    # If there is any error other than a failure to locate, report it
    die $@ if $@ && $@ !~ m/Can't locate Pod\/Coverage.+pm in \@INC/;

    # We'll prefer Pod::Coverage::CountParents
    eval "use Pod::Coverage::CountParents";
    die $@ if $@ && $@ !~ m/Can't locate Pod\/Coverage.+pm in \@INC/;
}

**Comment by pjcj** [comment]
Thanks for your report.

Could you please let me know which version of Devel::Cover you are using and attach the output of perl -V

**Comment by tripled1313** [comment]
This is perl, v5.8.8 built for x86_64-linux-thread-multi

Copyright 1987-2006, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.


Devel::Cover is version 1.29

**Comment by pjcj** [comment]
Ah, I'm afraid I'm not supporting 5.8. The minimum supported option is 5.10.0.

Unfortunately it seems that things are dying before you even get to the message explaining that, but if you look a few lines further down in Devel::Cover.pm (starting around line 114) you can see the details.

Can you upgrade to something a little newer?

If not, and you would like to fix things up to work with 5.8.8 then I may be willing to accept patches but lets discuss things before you get too far.

**Comment by tripled1313** [comment]
At this point in time I can't upgrade.  Is this a backwards compatible issue?  Is there an older version of Devel::Cover that might get me by until I can get perl upgraded?

**Comment by pjcj** [comment]
From https://github.com/pjcj/Devel--Cover/blob/master/lib/Devel/Cover.pm#L115 I see that version 1.23 was the last version which explicitly supported 5.8.  It is possible that later versions also worked but I can't be sure about that.

**Comment by tripled1313** [comment]
Where can I get an older version so I can give it a try?  And thanks for the assistance.

**Comment by pjcj** [comment]
You can jump to specific versions on metacpan and then use the download link.  You'll need https://cpan.metacpan.org/authors/id/P/PJ/PJCJ/Devel-Cover-1.23.tar.gz I think.

**Comment by tripled1313** [comment]
I was able to get 1.23 installed, and it worked, thanks for your help
