### ISSUE TITLE
Counts for criterion are not displayed in the coverage report of merged databases

### ISSUE THREAD

**Issue by emiliaboyadjieva** [pjcj/Devel--Cover#198]
I encountered a problem in the Devel::Cover that when I merge more than 2 databases coverage counts for criterion  are not displayed in the report. After some investigation in the Devel::Cover code I have found that the merge of the Structure.pm uses the same subroutine _merge_hash as the DB.pm. I believe this is wrong. For the DB.pm the counts are supposed to be added, but Structure.pm holds data for the lines in the source files; thus after merge the lines get added as many times as merges have been done and therefore in the report the lines couldn't be found. Furthermore I have encountered another issue, which has to to with #150 - I think during merge the structure is read from the filesystem from the first read database instead of the merged structure in the memory and therefore those warnings are being displayed

**Comment by pjcj** [comment]
Closed with #199
