### ISSUE TITLE
Devel::Cover should ignore .AppleDouble files

### ISSUE THREAD

**Issue by DrHyde** [pjcj/Devel--Cover#200]
I often work in a Linux VM on a Mac, with the VM's filesystem exported using netatalk so I can easily look at Devel::Cover HTML reports on the Mac. The Mac drops annoying .AppleDouble files all over the place leading to errors on the VM like "found .AppleDouble in /home/dc/MyProject/cover_db at /opt/perlbrew/perls/perl-5.22.3/lib/site_perl/5.22.3/x86_64-linux/Devel/Cover/DB.pm line 203."

.AppleDouble files are meaningless to everything except the Mac Finder, and can be deleted with impunity, so I suggest that Devel::Cover should ignore their presence.

**Comment by pjcj** [comment]
I do rather dislike systems which think they can just go adding files wherever they wish.

I have implemented your suggestion with 37e63dd which will be in the next release.  Thanks very much for your report.
