### ISSUE TITLE
Missing coverage if -M$Module is used

### ISSUE THREAD

**Issue by eserte** [pjcj/Devel--Cover#204]
If during a coverage run another perl script is called, then it seems to matter if modules in this script are included with the command line option `-M$Module` or with a normal `use $Module` within the script. Using the former variant there's no coverage collected for $Module.

Here's a test setup. `foo.pl` looks like this:
```
#!/usr/bin/perl

my @cmd;
if (@ARGV) {
    @cmd = ($^X, "-I.", "-MBla", "-e", 'Bla::hello()');
} else {
    @cmd = ($^X, "-I.", "-e", 'use Bla; Bla::hello()');
}
system @cmd;

__END__
```

And `Bla.pm` looks like this:
```
package Bla;

sub hello {
    warn "hello, world";
}

1;

__END__
```

The working variant:
```
$ rm -rf cover_db && env PERL5OPT=-MDevel::Cover perl foo.pl && cover
...
----------------------------------- ------ ------ ------ ------ ------ ------
File                                  stmt   bran   cond    sub   time  total
----------------------------------- ------ ------ ------ ------ ------ ------
Bla.pm                               100.0    n/a    n/a  100.0    n/a  100.0
...
```

The non-working variant:
```
$ rm -rf cover_db && env PERL5OPT=-MDevel::Cover perl foo.pl alternative && cover
...
----------------------------------- ------ ------ ------ ------ ------ ------
File                                  stmt   bran   cond    sub   time  total
----------------------------------- ------ ------ ------ ------ ------ ------
Bla.pm                                 0.0    n/a    n/a    0.0    n/a    0.0
...
```

**Comment by ikg1hd** [comment]
Hi,

I think the cause is that Perl processes options from the command line before processing PERL5OPT, and options are processed before code, and that D::C can cover only modules which were loaded after D::C was loaded.
In your non-working variant, `-MBla` (command line) is processed before `-MDevel::Cover` (PERL5OPT), while in the working variant, `-MDevel::Cover` (PERL5OPT) is processed before `use Bla`.

Kind regards.
Thomas

**Comment by eserte** [comment]
@ikg1hd Thanks for your explanation. Then maybe this could go into a short documentation notice.

**Comment by pjcj** [comment]
Thank you, Thomas, for this explanation, which is quite correct.  I have added a note in the documentation with 5a3ed3ba3f731b809f6c2c0eb00674935648a2ce.  And thanks, Slaven, for reporting the problem.
