### ISSUE TITLE
need to fix $VERSION in cover script to support Perl5.8

### ISSUE THREAD

**Issue by bayashi** [pjcj/Devel--Cover#206]
below code does not work under Perl5.8.

    BEGIN { $VERSION //= $Devel::Cover::Inc::VERSION }

cover script

    our $VERSION = '1.29'; # VERSION

I would like `cover` to work under Perl5.8. 

Thank you!

**Comment by ikg1hd** [comment]
Hi,

according to #197, Perl 5.8 is not supported for D::C 1.24+.

Kind regards,
Thomas

**Comment by bayashi** [comment]
@ikg1hd 
Oh, I didn't know that. And I understand.

Thank you
bayashi
