### ISSUE TITLE
XS: 50% branch cover reported for unconditional SvPV(...) assignment to a variable

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#214]
Example from Net::DNS::SEC

Assignment statements at SEC.xs, lines 385 and 387

376 |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
377 |   |   |   |   |   |   | int
378 |   |   |   |   |   |   | RSA_set0_factors(RSA *r, SV *p_SV, SV *q_SV)
379 |   |   |   |   |   |   | PREINIT:
380 |   |   |   |   |   |   | BIGNUM *p;
381 |   |   |   |   |   |   | BIGNUM *q;
382 |   |   |   |   |   |   | unsigned char *bin;
383 |   |   |   |   |   |   | STRLEN len;
384 |   |   |   |   |   |   | CODE:
385 | 14 | 50 |   |   |   |   | bin = (unsigned char*) SvPV( p_SV, len );
386 | 14 |   |   |   |   |   | p = BN_bin2bn( bin, len, NULL );
387 | 14 | 50 |   |   |   |   | bin = (unsigned char*) SvPV( q_SV, len );
388 | 14 |   |   |   |   |   | q = BN_bin2bn( bin, len, NULL );
389 | 14 |   |   |   |   |   | RETVAL = checkerr( RSA_set0_factors( r, p, q ) );
390 |   |   |   |   |   |   | OUTPUT:
391 |   |   |   |   |   |   | RETVAL
392 |   |   |   |   |   |   |

**Comment by pjcj** [comment]
Without checking, I suspect that the problem here will be that SvPV is a macro which expands to a conditional.  In which case I'm not sure what could be done.  Perhaps some uncoverable extension?

**Comment by pjcj** [comment]
@rwfranks: It looks like you have refactored the code to solve the immediate problem. I think that's the pragmatic solution here.
The data Devel::Cover is using is coming from gcov, and it's the C macro system which is doing us in.  No doubt this is also a problem for C projects, and if the gcc folk haven't been able to solve it, I'm not sure we're going to be able to do better.
One area we could probably improve on, though, is that I'm not sure there's any benefit in providing coverage of perl's own header files when they're used from XS code.  We should probably ignore them the same way that we ignore core perl modules.

**Comment by pjcj** [comment]
See also #111

**Comment by rwfranks** [comment]
On 18 September 2018 at 20:46, Paul Johnson <notifications@github.com>
wrote:

> @rwfranks <https://github.com/rwfranks>: It looks like you have
> refactored the code to solve the immediate problem. I think that's the
> pragmatic solution here.
>
Yes.  I justified that to myself on the grounds that I already know that
there is no magic involved in these particular cases.
Obviously, that justification is not valid in the general case.

The data Devel::Cover is using is coming from gcov, and it's the C macro
> system which is doing us in. No doubt this is also a problem for C
> projects, and if the gcc folk haven't been able to solve it, I'm not sure
> we're going to be able to do better.
>
I did suggest post-processing the results, and still think that is an
avenue worth exploring.


> One area we could probably improve on, though, is that I'm not sure
> there's any benefit in providing coverage of perl's own header files when
> they're used from XS code. We should probably ignore them the same way that
> we ignore core perl modules.
>
I am certain that there is no benefit.

**Comment by rwfranks** [comment]
Overtaken by issue #344
