### ISSUE TITLE
use of 5.10 syntax

### ISSUE THREAD

**Issue by karenetheridge** [pjcj/Devel--Cover#226]
Devel::Cover::DB uses the `//` operator, which requires perl 5.10.  Either the minimum perl version in Makefile.PL needs to be incremented, or this syntax replaced with `||`.

Looks like this was introduced by commit ff31373b914 (pull request #199).

**Comment by karenetheridge** [comment]
I see lots of other uses of `//` throughout, so I guess this is intentional. Please bump the minimum perl version so that users know they should do coverage tests on a more modern perl.

**Comment by Leont** [comment]
I also just ran into this.

**Comment by pjcj** [comment]
Thanks very much for this report.  I have now made the minimum requirement of 5.10.0 official.  I've also added you to the Contributors file - please let me know or send me a pull request if you would like to remove or change the entry.

I'll get this in the next release.
