### ISSUE TITLE
cover -write fails silently

### ISSUE THREAD

**Issue by degeberg** [pjcj/Devel--Cover#232]
After upgrading from 1.24 to 1.31, a command like this no longer works:

```bash
cover -write cover_db/merged cover_db/*
```

It just exits without any output and an exit status of `1`. If we are supposed to call `cover` differently in new versions, I can't find it mentioned in the changelog or the documentation. Either way it probably shouldn't fail silently.

We fixed our particular problem by applying the following patch:

```patch
--- a/bin/cover
+++ b/bin/cover
@@ -203,7 +203,7 @@ sub main {
         }
     } @{$Options->{report}} ];
 
-    exit 1 if !@{$Options->{report}} && !$Options->{delete};
+    exit 1 if !@{$Options->{report}} && !$Options->{delete} && !exists $Options->{write};
 
     $Options->{annotations} = [];
     for my $a (@{$Options->{annotation}}) {
```

I'm not entirely sure if this is a correct fix, but it seems reasonable based on the following (in `get_options`):

```perl
    $Options->{report} = ["html"]
        if !@{$Options->{report}} && !exists $Options->{write};
```

**Comment by pjcj** [comment]
Thanks very much for this!

I think your analysis is correct, and I broke this when I added support for multiple reports.

I have applied your patch, and added you to the contributors file.  If you would like to change or remove your entry, please let me know or send me a pull request.

Thanks again.
