### ISSUE TITLE
Should Devel::Cover::Test and Devel::Cover::Inc be part of the installation?

### ISSUE THREAD

**Issue by jkahrman** [pjcj/Devel--Cover#237]
Devel::Cover::Test and Devel::Cover::Inc appear to only be used by Devel-Cover's tests. Additionally, Devel::Cover::Inc has a reference back to the source directory that Devel-Cover was built in. Should Devel::Cover::Test and Devel::Cover::Inc be part of the installation? Perhaps they should be in with the tests.

**Comment by jkahrman** [comment]
Not sure how I missed the Devel::Cover::Inc reference in Devel::Cover when I did my initial search.

**Comment by pjcj** [comment]
Thanks for taking the time to make a ticket and then doing the work to close it :)
