### ISSUE TITLE
recursive subs with __SUB__ cause segfault on perl 5.28

### ISSUE THREAD

**Issue by pjuhasz** [pjcj/Devel--Cover#243]
With Perl 5.28.2, Devel::Cover 1.31, the following program causes a segmentation fault with the error message "Deep recursion on subroutine "B::Deparse::deparse" at /usr/lib64/perl5/vendor_perl/Devel/Cover.pm line 1033": 

```
#!/usr/bin/perl

use feature ':5.16';
use Test::More;

sub recursive {
	return $_[0] ? __SUB__->($_[0]-1) : 0;
}

ok 1;
done_testing;
```

The exact command line: `perl -MDevel::Cover=-db,/tmp/foo.db fail.t`

The same command with the same program on a different system with Perl 5.26.3, Devel::Cover 1.29 does not produce a segfault, it prints the coverage report and exits normally.

Rewriting the test program so that it pre-declares the `recursive` function, then refers to it by name eliminates the segfault, which points to the `__SUB__` token being the culprit.

**Comment by pjuhasz** [comment]
Apparently commit 8db956dc2ac6675d2f1f619663d22b35727514fc in Devel::Cover introduced the bug. Commenting out the lines added to `sub deparse` by that commit eliminates the segfault.

**Comment by pjuhasz** [comment]
Further investigation: there is a SVOP:const that causes B::Deparse::const_dumper to be called, which in turn calls Data::Dumper::Dump, and that causes the infinite recursion.

**Comment by larryl** [comment]
I just added a comment and reproducible test case to issue 285 (https://github.com/pjcj/Devel--Cover/issues/285) but I think it is the same as this issue.

**Comment by pjcj** [comment]
I have merged the fix and this should be in the next release.  Thank you for the report, the test case (which I have added as a test) and the fix!
