### ISSUE TITLE
test failures on Perl 5.31.5 and later

### ISSUE THREAD

**Issue by rwfranks** [pjcj/Devel--Cover#260]
Test Summary Report
-------------------
t/e2e/asignature.t        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=80, Tests=93, 52 wallclock secs ( 0.28 usr  0.05 sys + 40.26 cusr  7.37 csys = 47.96 CPU)
Result: FAIL
Failed 1/80 test programs. 1/93 subtests failed.
make: *** [Makefile:1252: test_dynamic] Error 255

**Comment by pjcj** [comment]
Thanks very much for reporting this.  It has been fixed in 164759f3694a9d1c85be9c5c1e0a4e3879dca400 and will be in the 1.34 release.
