### ISSUE TITLE
Devel::Cover::Subroutine doc bug

### ISSUE THREAD

**Issue by bkerin** [pjcj/Devel--Cover#262]
The Devel::Cover::Subroutine has in its NAME section this line:

     Devel::Cover::Statement - Code coverage metrics for Perl

and in it's SYNOPSIS section this line:

     use Devel::Cover::Statement;

There may be other similar errors in other modules, I haven't checked

**Comment by pjcj** [comment]
Thanks very much!  This has been fixed in 12f586b.  I think the other modules are correct in this respect at least.

I'd be happy to add you to the Contributors file.  If you'd like that, please either send me a pull request or let me know the line you'd like in that file.

Thanks again.
