### ISSUE TITLE
Error in 1.35 if -db option used with an absolute path

### ISSUE THREAD

**Issue by sdt** [pjcj/Devel--Cover#267]
The change in 793c0125979fea727470cc0ee669841849188df4 breaks things if `$DB` is an absolute path.

We run with `-db /app-path/cover-db` and now fail with: 
`Can't mkdir /app-path/app-path/timesheets-api/cover-db`

It looks like the `catdir` here should only be applied if `$DB` is a relative path. 

https://github.com/pjcj/Devel--Cover/blob/793c0125979fea727470cc0ee669841849188df4/lib/Devel/Cover.pm#L349 

In my case the cwd is `/app-path`.

I can work around this easily enough, but I suspect the intention is to allow absolute paths here.

**Comment by kevinval** [comment]
This actually completely breaks `bin/cover` as far as I can tell. Using `bin/cover` an absolute path is concatenated to $DB already and then the same thing is done again, so we end up with:

`/whatever/is/current/cwd/whatever/is/current/cwd/cover_db`

**Comment by rflett** [comment]
We have run into the same issue, and have rolled back to 1.33 as a workaround for now.

**Comment by kevinval** [comment]
Same here, rolled back to 1.33 and just confirmed our CI passed.

**Comment by pjcj** [comment]
Thanks for the report and discussion.

This looks to be a result of #253 

I'll see about getting a fix in place as soon as possible.

**Comment by pjcj** [comment]
Fixed in 0fdefd5

I'll get a new release out as soon as possible.

**Comment by pjcj** [comment]
Fixed in release 1.36

**Comment by sdt** [comment]
Thank you 👍
