### ISSUE TITLE
Uncoverable subroutines with signatures

### ISSUE THREAD

**Issue by perlpunk** [pjcj/Devel--Cover#287]
It appears that each argument in a subroutine signature counts as one statement.

We are using experimental signatures in our code.
We also include code under `t/` in the coverage report.
There are various functions there that are only called if a test fails, so they are uncoverable.

Now, with using signatures, we would have to add
```
# uncoverable statement count:1
# uncoverable statement count:2
# uncoverable statement count:3
# uncoverable statement count:4
sub only_called_when_some_test_fails ($x, $y) {
```
before a subroutine with a signature with 2 arguments, for example.
It would be good to have a way around that, like `count:all` for example.
Ideally, using `# uncoverable subroutine` would already do that, but I guess it's not trivial.

**Comment by Ovid** [comment]
I agree that this would be lovely to fix. Hits me all the time. Plus, with v5.26.0 being released and signatures no longer experimental, it's becoming more important to deal with.

**Comment by perlpunk** [comment]
@Ovid `s/5.26/5.36/` =)

**Comment by Ovid** [comment]
@perlpunk Oops. Fixed, thanks :)

**Comment by perlpunk** [comment]
With the 1.37 version #288 was released, so I will close this issue.
Thanks!
