### ISSUE TITLE
Convert Devel-Cover db to lcov data format

### ISSUE THREAD

**Issue by henry2cox** [pjcj/Devel--Cover#327]
I would like to use some features of [lcov](https://github.com/linux-test-project/lcov) to analyze perl components in some projects.  lcov itself is one such project :-)

Specifically, I would like differential coverage as well as date binning (described in [https://arxiv.org/abs/2008.07947](https://arxiv.org/abs/2008.07947) or [https://ieeexplore.ieee.org/document/9438597](https://ieeexplore.ieee.org/document/9438597)) - as well as to include perl components a unified project  coverage report, and to add perl code to the coverage criteria used by the corresponding jenkins job.

The easiest way I can think of to do that is to translate Devel-Cover data into lcov .info file format.

The lcov ".info" file format is pretty simple - and more-or-less described in the [geninfo man page](https://github.com/linux-test-project/lcov/blob/master/man/geninfo.1#L989).

Brief perusal suggests that it is not spectacularly difficult to write a screen scraper to convert the Devel-Cover HTML report to lcov format, for line, branch, and subroutine types - but it would likely be easier to write the format directly.
I wondered if somebody had already done either of those - and could point me to the code.

Thanks

Henry

**Comment by henry2cox** [comment]
Addressed by `perl2lcov` script in lcov repo - see commit 7bbc2b80b6d8,

**Comment by pjcj** [comment]
Thanks for doing this!
