### ISSUE TITLE
t/e2e/adbm_cond.t fails (if DBM::Deep is installed?)

### ISSUE THREAD

**Issue by eserte** [pjcj/Devel--Cover#336]
The test suite fails on some of my smokers, probably only on systems where DBM::Deep is installed:
```
t/e2e/adbm_cond.t .................. 
No subtests run 
```

**Comment by pjcj** [comment]
Ah, yes, and I know why.  Fortunately it’s “just” a testing problem.  Thank you!

— 
Paul Johnson - ***@***.***

**Comment by pjcj** [comment]
Fixed in 1.42
