### ISSUE TITLE
Devel::cover doesn't play nicely with JSON

### ISSUE THREAD

**Issue by sanbeg** [pjcj/Devel--Cover#55]
I see a lot of warnings like
Subroutine main::to_json redefined at (eval 2673)[t/00_required_modules.t:54] line 2.
Prototype mismatch: sub main::to_json ($) vs ($@) at (eval 2673)[t/00_required_modules.t:54] line 2.

As well as JSON related test failures when running test coverage on a large project.  Tests all pass if Devel::cover isn't used.

**Comment by pjcj** [comment]
Thanks very much for the report, but I've not been able to reproduce this.  @sanbeg: if this is still a problem please reopen the ticket and provide some more information.  Thanks!
