### ISSUE TITLE
Devel::Cover::DB: Need method to confirm existence of database

### ISSUE THREAD

**Issue by jkeenan** [pjcj/Devel--Cover#60]
For the purpose of working on Devel::CoverX::Archive (https://github.com/jkeenan/Devel--CoverX--Archive), I need to be able to:
1. Verify that a valid Devel::Cover database exists in a given directory (typically, 'cover_db').
2. Get what is in some sense the "runtime" of the coverage report run on that database.

App::ArchiveDevelCover avoided these problems by scraping the HTML output of 'cover'.  It would be better to get this information directly from the Devel::Cover DB, as that would eliminate a dependency on a particular output format.

In my first attempt to verify the existence of a Devel::Cover DB, I checked for the existence of a 'cover.NN' file, a 'digests' file, and 'runs' and 'structure' directories underneath the cover_db/ directory.  This is unsatisfactory as well, as it depends on particular implementation details of Devel::Cover which are subject to change in the future.

It would be better to have a function -- probably a Devel::Cover::DB method call -- that would give a yes or no answer as to whether a valid Devel::Cover DB exists in a given directory.

One complication:  I have come to realize that the structure underneath cover_db/ changes from the point where you have run tests with coverage requested to the point after you have run 'cover'.  So perhaps we need to identify two states rather than one:

a. You have run tests with coverage requested.

b. You have both run tests with coverage requested and called 'cover' to generate output data.

From the point of view on Devel::CoverX::Archive, the "runtime" we need is the time at which 'cover' was most recently run, i.e., it should designate the time of (b) rather than (a).  That's because I envision the user running a command-line tool called 'archive_coverage' after running 'cover'.

Thank you very much.
Jim Keenan

**Comment by pjcj** [comment]
Hello Jim,

The code in this area has changed a little in the last four years, hopefully for the better, but maybe not.  In any case, I'm going to close this now, but please feel free to repoen it if you ever get back to this and find it still problematic.

Thanks!
