### ISSUE TITLE
cpancover: No coverage written if module on command-line is not in directory named by 'directory' option

### ISSUE THREAD

**Issue by jkeenan** [pjcj/Devel--Cover#62]
Assume that there exist the following directories -- "modules" in the language of cpancover:

```
/Users/jimk/tmp/research/List-Compare-0.37
/Users/jimk/tmp/research/Text-CSV-Hashify-0.05
```

The following code works, i.e., it runs coverage analysis on a list of modules found underneath a common directory and updates the summary files as needed.

```
$ perl bin/cpancover -d /Users/jimk/tmp/research/ --outputdir=/Users/jimk/tmp/results/

$ cat /Users/jimk/tmp/results/cpan_cover.csv
release,distribution,link,branch_class,branch_details,branch_pc,condition_class,condition_details,condition_pc,pod_class,pod_details,pod_pc,statement_class,statement_details,statement_pc,subroutine_class,subroutine_detials,sbroutine_pc,total_class,total_details,total_pc
,Text-CSV-Hashify-0.05,1,Text-CSV-Hashify-0.05/coverage.html,c0,25 / 48, 52.08,c0,13 / 23, 56.52,c1,6 / 7, 85.71,c1,76 / 100, 76.00
,List-Compare-0.37,1,List-Compare-0.37/coverage.html,c0,295 / 442, 66.74,c0,111 / 186, 59.68,c0,89 / 163, 54.60,c0,1381 / 1913, 72.19
```

Now, let's assume that we do _not_ supply a directory for the '-d' option _and_ that we supply a path to one of those modules as a command-line argument:

```
$ perl  bin/cpancover --outputdir=/Users/jimk/tmp/results /Users/jimk/tmp/research/Text-CSV-Hashify-0.05/
```

In this case, I would assume that coverage analysis would be conducted as needed on /Users/jimk/tmp/research/Text-CSV-Hashify-0.05/ and the results written to the directory which is the value of the '--outputdir' option.  However, no specific data about the module is written to the results files.

```
$ cat /Users/jimk/tmp/results/cpan_cover.csv
release,distribution,link,branch_class,branch_details,branch_pc,condition_class,condition_details,condition_pc,pod_class,pod_details,pod_pc,statement_class,statement_details,statement_pc,subroutine_class,subroutine_detials,sbroutine_pc,total_class,total_details,total_pc
```

As best I can tell, the cause of this problem is located in these lines from subroutine write_html():

```
    for my $module (sort keys %$results)
    {
        my $dbdir = "$Options->{directory}/$module/cover_db";
        next unless -d $dbdir;
        chdir "$Options->{directory}/$module";
        print "Adding $module from $dbdir\n";
```

If no value is specified for '-d' on the command-line, $Options->{directory} defaults to the current working directory.  If, however, the module being analyzed is not located underneath that directory, then '-d $dbdir' returns false and no data gets written to the results file.

**Comment by pjcj** [comment]
Hello Jim,

In the meantime, I have implemented my idea above, and cpancover is now based on a generalised idea of reporting on coverage for a number of modules.  The Collection module is the one doing the work here.

So I am going to close this now and thank you for nudging me in the right direction ;)
