### ISSUE TITLE
Devel::Cover:DB gives "Filehandle STDOUT reopened as $fh only for input" warnings

### ISSUE THREAD

**Issue by newatlantis** [pjcj/Devel--Cover#70]
When I run "prove" with Devel::Cover on the demo test script below, I get these warnings:

```
Filehandle STDOUT reopened as $fh only for input at /Library/Perl/5.12/darwin-thread-multi-2level/Devel/Cover/DB/IO/JSON.pm line 39.
Filehandle STDOUT reopened as $fh only for input at /Library/Perl/5.12/darwin-thread-multi-2level/Devel/Cover/DB/Structure.pm line 218.
```

I know they are just warnings. But I'm wondering if they indicate a problem in Devel::Cover::DB. Would it be a mistake to put "no warnings 'io';" before the open commands on the Devel::Cover::DB module lines indicated above? Details follow.

Demo test script:

```
#!/usr/bin/perl
use Pod::Perldoc;
use Test::More tests => 1;
$ARGV[0] = 'perlrun';
ok(!Pod::Perldoc->run());
```

Environment details:

```
$ perl -v | grep ^This
This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level

$ perl -MDevel::Cover -e 'print $Devel::Cover::VERSION'
1.08

$ prove --version
Name "main::running_under_some_shell" used only once: possible typo at /usr/bin/prove5.12 line 3.
TAP::Harness v3.28 and Perl v5.12.4

$ uname -mrv
12.4.0 Darwin Kernel Version 12.4.0: Wed May  1 17:57:12 PDT 2013; root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64
```

Full output of "prove" invocation:

```
$ HARNESS_PERL_SWITCHES=-MDevel::Cover prove test.t
Name "main::running_under_some_shell" used only once: possible typo at /usr/bin/prove5.12 line 3.
test.t .. 1/1 Filehandle STDOUT reopened as $fh only for input at /Library/Perl/5.12/darwin-thread-multi-2level/Devel/Cover/DB/IO/JSON.pm line 39.
Filehandle STDOUT reopened as $fh only for input at /Library/Perl/5.12/darwin-thread-multi-2level/Devel/Cover/DB/Structure.pm line 218.
test.t .. ok   
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.07 usr  0.00 sys +  0.47 cusr  0.06 csys =  0.60 CPU)
Result: PASS
```

**Comment by pjcj** [comment]
Wow - I am really sorry that it has taken me so long to reply here.

In the meantime, I have completely rewritten the IO routines and, although I can't repeat the problem you report here, the better IO architecture seems like it might be more resilient to such problems.

So I'm going to close the ticket but, if you find that this is still a problem for you, please feel free to reopen it.

Thanks very much for your report, and sorry again for the lengthy delay in getting to it.

**Comment by newatlantis** [comment]
Thank you, Paul!
