### ISSUE TITLE
t/e2e/aoverload_bool2.t failure

### ISSUE THREAD

**Issue by dsteinbrunner** [pjcj/Devel--Cover#85]
Here is the log from my Mac OS X 10.9.2 install:
https://gist.github.com/dsteinbrunner/10018470

**Comment by pjcj** [comment]
Thanks very much for this report.  I remember this being a problem on BSD based systems in the past, but it was fixed a while ago.

I'm going to close the ticket, but if it is still a problem with the latest release, please feel free to reopen it.

Thanks!
