### ISSUE TITLE
Missing Documentation: How to mark branches as uncoverable if "elsif" is involved

### ISSUE THREAD

**Issue by xtaran** [pjcj/Devel--Cover#99]
I'd be nice to have at least an example which explains how to mark the empty `else` block as uncoverable in the following pseudo-code:

``` perl
if ($a) {
    ...;
} elsif ($b) {
    ...;
}
...;
```

**Comment by pjcj** [comment]
This has been added with 878ab7dff7844907d7e678f39333cf220167dc18

Thanks very much for your report!
